replace luci-app-athena-led

diff --git a/package/emortal/luci-app-athena-led/root/etc/init.d/athena_led b/package/emortal/luci-app-athena-led/root/etc/init.d/athena_led
--- a/package/emortal/luci-app-athena-led/root/etc/init.d/athena_led
+++ b/package/emortal/luci-app-athena-led/root/etc/init.d/athena_led
@@ -5,38 +5,56 @@ STOP=99
 USE_PROCD=1
 PROG=/usr/sbin/athena-led
 
+check_binary() {
+    if [ ! -x "$PROG" ]; then
+        logger -t athena-led -p daemon.error "Binary $PROG not found or not executable"
+        return 1
+    fi
+    return 0
+}
+
 start_service() {
-  config_load 'athena_led'
-  local cfg='config'
+    config_load 'athena_led'
+    local cfg='config'
 
-  config_get_bool enabled "$cfg" 'enable' '0'
-  if [ "$enabled" -eq 0 ]; then
-    logger "athena-led Service is disabled, not starting"
-    return 1
-  fi
+    config_get_bool enabled "$cfg" 'Enabled' '0'
+    if [ "$enabled" -eq 0 ]; then
+        logger -t athena-led -p daemon.info "Service is disabled"
+        return 1
+    fi
 
-  local status seconds lightLevel option value
-  config_get status $cfg 'status' ' '
-  config_get seconds $cfg 'seconds' '5'
-  config_get lightLevel $cfg 'lightLevel' '5'
-  config_get option $cfg 'option' 'date timeBlink'
-  config_get value $cfg 'value' 'abcdefghijklmnopqrstuvwxyz0123456789+-*/=.:：℃'
-  config_get url $cfg 'url' 'https://www.baidu.com'
-  config_get tempFlag $cfg 'tempFlag' '4'
+    check_binary || return 1
 
-  procd_open_instance
-  procd_set_param command $PROG -status "${status}" -seconds "${seconds}" -lightLevel "${lightLevel}" -option "${option}" -value "${value}" -url "${url}" -tempFlag "${tempFlag}"
-  procd_set_param respawn
-  procd_close_instance
+    local status seconds lightLevel option value url tempFlag
+    config_get status "$cfg" 'SideStatusIndicator' ''
+    config_get seconds "$cfg" 'IntervalTime' '5'
+    config_get lightLevel "$cfg" 'LightLevel' '5'
+    config_get option "$cfg" 'DisplayMode' 'date timeBlink'
+    config_get value "$cfg" 'CustomText' 'abcdefghijklmnopqrstuvwxyz0123456789+-*/=.:：℃'
+    config_get url "$cfg" 'RemoteText' 'https://ifconfig.me'
+    config_get tempFlag "$cfg" 'TemperatureSensor' '4'
 
+    procd_open_instance
+    procd_set_param command "$PROG" \
+        --status "${status}" \
+        --seconds "${seconds}" \
+        --light-level "${lightLevel}" \
+        --option "${option}" \
+        --value "${value}" \
+        --url "${url}" \
+        --temp-flag "${tempFlag}"
+    procd_set_param respawn
+    procd_set_param stderr 1
+    procd_close_instance
+
+    logger -t athena-led -p daemon.info "Service started"
 }
 
-service_triggers(){
-	procd_add_reload_trigger "athena_led"
+service_triggers() {
+    procd_add_reload_trigger "athena_led"
 }
 
-reload_service()
-{
-	stop
-	start
+reload_service() {
+    stop
+    start
 }
